### ISSUE TITLE
Make installable Python package

### ISSUE THREAD

**Issue by mikekryjak** [FusionDLS/FusionDLS#10]
DLS is currently just a bunch of scripts and we do not provide the user with a means to install it into their Python environment or with any information about dependencies. I propose to keep things simple and just add a `setup.py` to allow an editable install with `pip install -e .`. We can look at putting it on `PyPi` at a later stage.

**Comment by smth-27** [comment]
I'd like to contribute to this issue.

**Comment by mikekryjak** [comment]
Hi @smth-27! Thanks for the offer to help, we appreciate it :) 
Feel free to create a PR!

**Comment by ZedThree** [comment]
Closed in #26
