### ISSUE TITLE
Package name

### ISSUE THREAD

**Issue by ZedThree** [FusionDLS/FusionDLS#24]
If we want to get this onto PyPI, then the package needs a name. Unfortunately there's quite a few existing packages with some variation on `dls`: https://pypi.org/search/?q=dls -- these turn out to belong to Diamond Light Source.

So, it might be wise to come up with a more unique name for the package

**Comment by mikekryjak** [comment]
Thanks @ZedThree. It's tricky to come up with a completely different name. How about `dls-extended` or `detachment-location-sensitivity`? The first one looks quite similar to the ones you showed in that list, and the latter is quite long. Which in your experience would be less bad?

**Comment by cydcowley** [comment]
How about fusion-DLS?
________________________________

**Comment by ZedThree** [comment]
`fusiondls` looks good to me -- short and sweet, and most importantly, no clashes on PyPI!

**Comment by mikekryjak** [comment]
Sounds good to me.
